### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by nmfm** [bitcraft/pyscroll#48]
Using the latest release or the master branch I get aTypeError just importing pyscroll:

```
$ python --version
Python 3.8.10
```

Traceback:
```
======================================================================
ERROR: pyscroll (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyscroll
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/nuno/Dev/Python/pyscroll/pyscroll/__init__.py", line 2, in <module>
    from .orthographic import BufferedRenderer
  File "/home/nuno/Dev/Python/pyscroll/pyscroll/orthographic.py", line 11, in <module>
    from .common import surface_clipping_context, RectLike
  File "/home/nuno/Dev/Python/pyscroll/pyscroll/common.py", line 6, in <module>
    RectLike = Union[Rect, tuple[Any, Any, Any, Any]]
TypeError: 'type' object is not subscriptable


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

**Comment by bitcraft** [comment]
Thanks for reporting this. I inadvertently removed support for python 3.8
when adding type annotations.  You can manually remove the type annotations
as a work around until I get it fixed.

**Comment by bitcraft** [comment]
should be fixed now

**Comment by nmfm** [comment]
I confirm it's fixes. Thanks!
